menu:
    Blog: /
    Archive: /archives/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: 
duoshuo: seansun

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
